[app]
 Key = "GDSDWW1DSADSADSAWDRK"   
 HttpPort = 8023   
 # 日志配置
 # level:debug/info/warn/error/panic/fatal 
[zaplog]
 director = 'runtime/log'
 level = 'debug' 
 #Jwt 
[jwt]
JwtSecret = "ADSDWW#DSADSADSAWJJK"
BufferTime = 8640     #单位秒,缓冲时间
ExpiresTime = 8640000    #单位秒,过期时间
Issuer     = "chunDoc"

[upload]
Path = 'upload'   ###首尾不带"/"
MaxSize = 500   ##单位：M
AllowType = ["png", "jpeg", "jpg", "zip"]  

[pdf]
Path = 'runtime/pdf'
 